baseURL: 'https://euphonious-gumption-b6014e.netlify.app'
languageCode: en-us
title: My New Blog
theme: PaperMod


params:
  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  homeInfoParams:
        Title: I'm glad you're here wave
        Content: Welcome to my blog, where you can find lots of front-end developing knowledge and you can see how my programming journey goes :D

  socialIcons: 
        - name: "Facebook>"
          url: "<https://www.facebook.com/profile.php?id=100011552317797>"
        - name: "<GitHub>"
          url: "<https://github.com/Szymonbaczek/quickstart>"       


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30