baseURL: 'https://euphonious-gumption-b6014e.netlify.app'
languageCode: en-us
title: Symon The Rising Front-End Star
theme: PaperMod


params:
  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  homeInfoParams:
        Title: I'm glad you're here :D
        Content: Welcome to my blog, where you can find lots of front-end developing knowledge and you can see how my programming journey goes! <br><br> I try to describe in detail my struggles with various programming problems. As I put up this blog, I am comfortable with .html, .css, .md, git and creating a static page generator like Hugo. My native language is Polish, so I apologize for any language mistakes. <br><br> If you're looking for something on a specific topic, take a look at the tags section.
     
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30